# Generated by Django 2.2.4 on 2019-08-09 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0002_queueselector'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=256)),
                ('label', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='queueselector',
            name='owner',
        ),
        migrations.DeleteModel(
            name='LabelFilter',
        ),
        migrations.DeleteModel(
            name='QueueSelector',
        ),
    ]
