# Generated by Django 2.2.4 on 2019-08-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20190809_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuefilter',
            old_name='label',
            new_name='label_id',
        ),
    ]
