# Generated by Django 2.2.4 on 2019-08-10 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0005_proccessedemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProccessedEmail',
            new_name='ProcessedEmail',
        ),
    ]
