# Generated by Django 2.2.4 on 2019-08-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20190810_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedemail',
            old_name='proccessed_on',
            new_name='processed_on',
        ),
    ]
