# Generated by Django 2.2.4 on 2019-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20190811_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='subject',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
