# Generated by Django 2.2.4 on 2019-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_processedemail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='sent_to',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
