# Generated by Django 2.2.4 on 2019-08-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_processedemail_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedemail',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.QueueFilter'),
        ),
    ]
